# Generated by Django 3.1 on 2020-09-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('pais', models.CharField(max_length=30, verbose_name='Pais')),
                ('pasaporte', models.CharField(max_length=50, verbose_name='Pasaporte')),
                ('edad', models.IntegerField()),
                ('apelativo', models.CharField(max_length=10, verbose_name='Apelativo')),
            ],
            options={
                'verbose_name': 'La Persona',
                'verbose_name_plural': 'Las Personas',
                'db_table': 'Mi_tabla_persona',
            },
        ),
    ]
