# Generated by Django 3.1 on 2020-09-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=50, max_length=50, verbose_name='Apellidos')),
                ('nacionalidad', models.CharField(max_length=30, verbose_name='Nacionalidad')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
            ],
        ),
    ]
