# Generated by Django 3.1 on 2020-09-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
