# Generated by Django 3.1 on 2020-09-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_auto_20200901_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='autor',
            name='nombres',
            field=models.CharField(default='Nombre por defecto', max_length=50, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='edad',
            field=models.PositiveIntegerField(default=0, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(max_length=20, verbose_name='Nacionalidad'),
        ),
    ]
