# Generated by Django 3.1 on 2020-09-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prestammo',
            new_name='Prestamo',
        ),
    ]
