# Generated by Django 3.1 on 2020-09-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20200901_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'fecha'], 'verbose_name': 'El Libro', 'verbose_name_plural': 'Los Libros'},
        ),
    ]
